version: '3'
services:
  nginx:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/nginx:/var/log/nginx'
      - './images/config/nginx/:/etc/nginx/conf.d/'
    links:
      - php81
      - php74
      - mysqlv8
      - redis
  php81:
    build:
      context: ./images
      dockerfile: php81.Dockerfile
    container_name: php81
    restart: always
    ports:
      - '9003:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php81:/var/log/php-fpm.log'
      - './images/config/php81/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
  php80:
    build:
      context: ./images
      dockerfile: php80.Dockerfile
    container_name: php80
    restart: always
    ports:
      - '9005:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php80:/var/log/php-fpm.log'
      - './images/config/php80/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
  php74:
    build:
      context: ./images
      dockerfile: php74.Dockerfile
    container_name: php74
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php74:/var/log/php-fpm.log'
      - './images/config/php74/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './images/config/cronjob:/etc/cron.d'
  php71:
    build:
      context: ./images
      dockerfile: php71.Dockerfile
    container_name: php71
    restart: always
    ports:
      - '9001:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php71/:/var/log/php-fpm.log'
      - './images/config/php71/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
  mysqlv8:
    build:
      context: ./images
      dockerfile: mysql.Dockerfile
    container_name: mysqlv8
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3308:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './images/sql_dump/mysql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dbtest
  mariadb10:
    build:
      context: ./images
      dockerfile: mariadb.Dockerfile
    container_name: mariadb10
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3304:3306'
    volumes:
      - './data/mariadb:/var/lib/mysql'
      - './images/sql_dump/maria:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mariadb
  supervisor:
    image: php74:latest
    container_name: supervisor
    restart: always
    volumes:
      - '../projects:/var/www/html'
      - './images/config/php74/supervisor:/etc/supervisor/conf.d/'
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
  nestjs:
    build:
      context: ./images
      dockerfile: nestjs.Dockerfile
    container_name: nestjs
    restart: always
    working_dir: '/var/www/html/project-test'
    ports:
      - '3000:3000'
    volumes:
      - '../projects:/var/www/html'
