version: '3'
services:
  nginx:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/nginx:/var/log/nginx'
      - './images/config/nginx/:/etc/nginx/conf.d/'
    links:
      - php80
      - php74
      - mysqlv8
      - redis
  php80:
    build:
      context: ./images
      dockerfile: php80.Dockerfile
    container_name: php80
    restart: always
    ports:
      - '9005:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php80:/var/log/php-fpm.log'
      - './images/config/php80/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
  php74:
    build:
      context: ./images
      dockerfile: php74.Dockerfile
    container_name: php74
    restart: always
    ports:
      - '9008:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php74:/var/log/php-fpm.log'
      - './images/config/php74/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './images/config/cronjob:/etc/cron.d'
  php71:
    build:
      context: ./images
      dockerfile: php71.Dockerfile
    container_name: php71
    restart: always
    ports:
      - '9009:9000'
    volumes:
      - '../projects:/var/www/html'
      - './images/logs/php71:/var/log/php-fpm.log'
      - './images/config/php71/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './images/config/cronjob:/etc/cron.d'
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
  mysqlv8:
    build:
      context: ./images
      dockerfile: mysql.Dockerfile
    container_name: mysqlv8
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3308:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './images/sql_dump/mysql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: dbtest
  mariadb10:
    build:
      context: ./images
      dockerfile: mariadb.Dockerfile
    container_name: mariadb10
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3303:3306'
    volumes:
      - './data/mariadb:/var/lib/mysql'
      - './images/sql_dump/maria:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mariadb
  postgres14:
    image: postgres:14
    container_name: postgres14
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
      - './images/sql_dump/postgres:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_DB: dbtest
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
  nestjs:
    build:
      context: ./images
      dockerfile: nestjs.Dockerfile
    container_name: nestjs
    restart: always
    working_dir: '/var/www/html/project-test'
    ports:
      - '3000:3000'
      - '3979:3979'
      - '9200:9200'
      - '9201:9201'
      - '9229:9229'
      - '3001:3001'
      - '4000:4000'
    volumes:
      - '../projects:/var/www/html'
  mysql-master:
    image: mysqlv8:latest
    container_name: mysql-master
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3309:3306'
    volumes:
      - './data/mysql-master:/var/lib/mysql'
      - './images/sql_dump/mysql-master:/docker-entrypoint-initdb.d'
      - './images/config/mysql-master:/etc/mysql/conf.d'
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'replicate'
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  mysql-slave:
    image: mysqlv8:latest
    container_name: mysql-slave
    restart: always
    working_dir: '/usr/share/'
    ports:
      - '3310:3306'
    volumes:
      - './data/mysql-slave:/var/lib/mysql'
      - './images/sql_dump/mysql-slave:/docker-entrypoint-initdb.d'
      - './images/config/mysql-slave:/etc/mysql/conf.d'
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'replicate'
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
